from enum import StrEnum


class ErrorCode(StrEnum):
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"